---
# Configuration du load balancer
lb_port: 80
lb_method: "round_robin"  # Options: round_robin, least_conn, ip_hash

# Backend servers
backend_servers:
  - { name: "web1", ip: "web1", port: 80 }
  - { name: "web2", ip: "web2", port: 80 }

# Health check
health_check_interval: 10
health_check_fails: 3
